name: Reechup
favicon: null
layout_spectrum: 0.019802490482106805
typography_spectrum: 0.902618152089417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9402301842346787
  lightness: 0.3439631164073944
  saturation: 0.6476751046720892
  rhythmicContrast: 0.6669594140257686
purpose: []
